### ISSUE TITLE
Calculate distances between user genomes and find different genes

### ISSUE THREAD

**Issue by Tato14** [bio-miga/miga#100]
Sorry if this is kind of naive question.
I run MIGA for different set of WGS of bacterial samples (C acnes). I would like to know if there is any way to compare samples between them. I understand the ANI/AAI metrics kind of perform this but against a reference genome. What I am looking at is like a matrix of ANI/AAI distances between samples in order to infer relatedness between them.

Besides, I would like to pinpoint which genome sequences have the greatest differences between two different conditions. Is there any way to accomplish this with MIGA? If not, could you recommend me any other tool?
Again, sorry if this is not the proper pace to ask these questions. Thanks.

**Comment by lmrodriguezr** [comment]
Hello @Tato14 

MiGA does support this type of analysis, but we currently don't offer that option in the website (although it is a planned feature). These are the possible solutions we could offer for now:

1. **Install and run MiGA locally**. I can guide you through this if you have the computational capabilities in-house and some basic experience with the terminal. In the near feature we will offer a containerized MiGA where you'll be able to do this locally with no command-line experience, but this is not production-ready yet.
2. **Use the Science Gateway**. We're currently working on deploying MiGA in the NSF supercomputer (XSEDE) and currently have a web interface where you could do this. The output is not very friendly yet, and the website is not ready for launching, but if you want to join our group of beta-testers I would be happy to give you early access.
3. **Use ANI/AAI matrix instead**. We offer a web service called [Genome Matrix](http://enve-omics.ce.gatech.edu/g-matrix/) that can do exactly that. It doesn't have all the pre-processing and quality-control features that MiGA offers, but if you use both services you can get all you need. An important limitation of that service is that it has a maximum processing time of 5 days and it only runs with the BLAST+ engine (no option for faster Diamond/FastANI alternatives). This means that you cannot process more that ~50 genomes. Is your collection larger than that?

I expect we'll be able to offer a fully-integrated solution within the MiGA Online environment in the near future, but in the interim I hope at least one of these solutions would work for you.

Miguel.

**Comment by Tato14** [comment]
Hi @lmrodriguezr,

I have installed MIGA locally and I did most of the clade analysis starting with the fastq files following the tutorial from the MIGA website. However, for the aforementioned questions I am not sure _how_ to do it, meaning specific functions and input files.

I checked the Genome Matrix website and seems a great tool! You specify fasta files as inputs, are those the contigs that MIGA assembly (5th step) outputs? I have 40 genomes so the solution may work.

Thanks! J

**Comment by lmrodriguezr** [comment]
Dear @Tato14 I'm sorry for the long delay on answering. Are you still experiencing this issue?

**Option 2** is currently in a beta-testers phase, if you're interested I could add you to our list of early-access testers.

For **option 3**: yes, you just need the assemblies.


Best,
Miguel.

**Comment by lmrodriguezr** [comment]
I'll close this issue for now, but please feel free to reopen it and/or contact us directly at http://support.microbial-genomes.org/
