### ISSUE TITLE
diamond + fastani option error (same input successful for default option)

### ISSUE THREAD

**Issue by jianshu93** [bio-miga/miga#101]
miga default option for blast successfully run and get all the expected output file. When using diamond and fastani, here is the error (everything for prodigal diamond et.al., seems fine): 

Probing running jobs
[2020-05-27 21:06:51 +0800] Queueing miga-project:p
[2020-05-27 21:06:51 +0800] Completed pid:61616 for 12C_DAS_al:d:pico266_DASbins_pico266_18
[2020-05-27 21:06:51 +0800] Spawned pid:16910 for 12C_DAS_al:p:miga-project
[2020-05-27 21:07:23 +0800] Probing running jobs
[2020-05-27 21:07:39 +0800] Completed pid:16910 for 12C_DAS_al:p:miga-project
[2020-05-27 21:07:42 +0800] Nothing else to do, shutting down
Exception: no implicit conversion of nil into String

DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/2.6.0/fileutils.rb:1569:in `path'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/2.6.0/fileutils.rb:1569:in `fu_each_src_dest0'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/2.6.0/fileutils.rb:418:in `cp'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0/lib/miga/cli/action/derep_wf.rb:89:in `representatives'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0/lib/miga/cli/action/derep_wf.rb:68:in `dereplicate'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0/lib/miga/cli/action/derep_wf.rb:56:in `perform'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0/lib/miga/cli/action.rb:32:in `launch'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0/lib/miga/cli.rb:197:in `launch'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0/bin/miga:10:in `<top (required)>'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/bin/miga:23:in `load'
DEBUG: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/bin/miga:23:in `<main>'

**Comment by lmrodriguezr** [comment]
Hello @jianshu93 
It looks like the `clade_finding` got interrupted but I'm not sure the yet why. Would you mind sharing the log file in `12C_DAS_al/daemon/p/miga-project.log`?

Did you use any additional parameters other than `--fast`?

Thanks!
Miguel

**Comment by jianshu93** [comment]
I did not use -fast but I use this: 

miga derep_wf --medoids --aai-p diamond --ani-p fastani -o 12C_DAS_allbin_usearch64_migadrep_fast /vd03/home/jianshu/pico/12C_DAS_allbin_usearch64/*.fasta -j 64 -t 1 

here is the log file (it looks like that it just stops at clade finding):


############
Date: 2020-05-27 21:07:00 +0800
Hostname: eco925-PowerEdge-R940xa
MiGA: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0
Task: haai_distances
Project: /vd03/home/jianshu/pico/12C_DAS_allbin_usearch64_migadrep_fast
------------
Cleaning databases...
.........|.........|.........|.........|.........|.........|.........|.........|.........|.........| 100%
#################################################################################################### Done

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> 
> haai <- read.table('miga-project.txt', sep='\t', h=T, as.is=TRUE);
> save(haai, file='miga-project.Rdata');
> if(sum(haai[,'a'] != haai[,'b']) > 0){
+   h <- hist(haai[haai[,'a'] != haai[,'b'], 'value'], breaks=100, plot=FALSE);
+   write.table(
+     cbind(h[['breaks']][-length(h[['breaks']])],
+       h[['breaks']][-1],h[['counts']]),
+     file='miga-project.hist', quote=FALSE, sep='\t',
+     col.names=FALSE, row.names=FALSE);
+ }
> 
> 
############
Date: 2020-05-27 21:07:19 +0800
Hostname: eco925-PowerEdge-R940xa
MiGA: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0
Task: aai_distances
Project: /vd03/home/jianshu/pico/12C_DAS_allbin_usearch64_migadrep_fast
------------

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> 
> aai <- read.table('miga-project.txt', sep='\t', h=T, as.is=TRUE);
> save(aai, file='miga-project.Rdata');
> if(sum(aai[,'a'] != aai[,'b']) > 0){
+   h <- hist(aai[aai[,'a'] != aai[,'b'], 'value'], breaks=100, plot=FALSE);
+   write.table(
+     cbind(h[['breaks']][-length(h[['breaks']])],
+       h[['breaks']][-1], h[['counts']]),
+     file='miga-project.hist', quote=FALSE, sep='\t',
+     col.names=FALSE, row.names=FALSE);
+ }
> 
> 
############
Date: 2020-05-27 21:07:27 +0800
Hostname: eco925-PowerEdge-R940xa
MiGA: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0
Task: ani_distances
Project: /vd03/home/jianshu/pico/12C_DAS_allbin_usearch64_migadrep_fast
------------

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> 
> ani <- read.table('miga-project.txt', sep='\t', h=T, as.is=TRUE);
> save(ani, file='miga-project.Rdata');
> if(sum(ani[,'a'] != ani[,'b']) > 0){
+   h <- hist(ani[ani[,'a'] != ani[,'b'], 'value'], breaks=100, plot=FALSE);
+   write.table(
+     cbind(h[['breaks']][-length(h[['breaks']])],
+       h[['breaks']][-1], h[['counts']]),
+     file='miga-project.hist', quote=FALSE, sep='\t',
+     col.names=FALSE, row.names=FALSE);
+ }
> 
> 
############
Date: 2020-05-27 21:07:34 +0800
Hostname: eco925-PowerEdge-R940xa
MiGA: /vd03/home/jianshu/anaconda33/install_with_tear/envs/miga/lib/ruby/gems/2.6.0/gems/miga-base-0.7.6.0
Task: clade_finding
Project: /vd03/home/jianshu/pico/12C_DAS_allbin_usearch64_migadrep_fast
------------
Warning message:
package ‘lattice’ was built under R version 3.6.3 
Warning message:
package ‘cluster’ was built under R version 3.6.3

**Comment by lmrodriguezr** [comment]
This issue should be resolved since v1.0. I will close it for now, but please feel free to reopen if you continue to experience it.

Thanks!
