### ISSUE TITLE
Part of MiGA is not working (aai and ani)

### ISSUE THREAD

**Issue by BJCampbelllab** [bio-miga/miga#124]
Hi MiGA team!
I installed MiGA via conda, and followed the installation instructions.  Got it to work for taxonomy calling.  However, when I go to use miga wf, for index (aai, ani), it gives me this error (listed below in miga.project.log) - even with three genomes.  It seems to go through all the steps until then.  For example, the log of one of the genomes is below.

Any help would be greatly appreciated!  I would do it on your website, but I have more than 50 genomes!

Best,
Barb

daemon/d log of one of the genomes:
######[ cds ]######
# Date: 2021-02-24 10:06:27 -0500
# Host: localhost.localdomain
# MiGA: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1
# Project: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test
# Dataset: GCA_000964845
#------------
Selected codon table: 11

######[ essential_genes ]######
# Date: 2021-02-24 10:06:41 -0500
# Host: localhost.localdomain
# MiGA: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1
# Project: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test
# Dataset: GCA_000964845
#------------
Temporal directory: /tmp/d20210224-47452-94wovf.
Searching models.
Parsing results.
Extracting sequences.
Done.

######[ ssu ]######
# Date: 2021-02-24 10:06:50 -0500
# Host: localhost.localdomain
# MiGA: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1
# Project: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test
# Dataset: GCA_000964845
#------------
index file ../../../05.assembly/GCA_000964845.LargeContigs.fna.fai not found, generating...
Reading list.
Filtering FastA.

######[ mytaxa_scan ]######
# Date: 2021-02-24 10:06:56 -0500
# Host: localhost.localdomain
# MiGA: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1
# Project: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test
# Dataset: GCA_000964845
#------------

######[ distances ]######
# Date: 2021-02-24 10:07:00 -0500
# Host: localhost.localdomain
# MiGA: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1
# Project: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test
# Dataset: GCA_000964845
#------------
Completeness: 93.7 %
Contamination: 1.8 %
Quality: 84.7
Options: {:aai_save_rbm=>"no-save-rbm", :thr=>1, :haai_p=>nil, :aai_p=>"diamond", :ani_p=>"fastani", :distances_checkpoint=>10}
Launching analysis
Launching analysis for reference dataset
Initializing databases (for_ref = true)
[ 2021-02-24 10:07:00 -0500 ] GCA_000011945
Accessing SQLite3 file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.haai.db.
Temporal directory: /tmp/d20210224-5878-4j4yfq.
Creating databases.
  Reading FastA file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.ess_genes.fa
    File contains 104 sequences.
  Reading FastA file: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test/data/07.annotation/01.function/01.essential/GCA_000011945.ess.faa
    File contains 102 sequences.
Running one-way comparisons.
Warning: [blastp] Examining 5 or more matches is recommended
Warning: [blastp] Examining 5 or more matches is recommended
[ 2021-02-24 10:07:04 -0500 ] GCA_000016625
Accessing SQLite3 file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.haai.db.
Temporal directory: /tmp/d20210224-6323-1r3mnek.
Creating databases.
  Reading FastA file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.ess_genes.fa
    File contains 104 sequences.
  Reading FastA file: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test/data/07.annotation/01.function/01.essential/GCA_000016625.ess.faa
    File contains 105 sequences.
Running one-way comparisons.
Warning: [blastp] Examining 5 or more matches is recommended
Warning: [blastp] Examining 5 or more matches is recommended
Accessing SQLite3 file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.aai.db.
Temporal directory: /tmp/d20210224-8200-ynnrh4.
Creating databases.
  Reading FastA file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.proteins.fa
    File contains 2492 sequences.
  Reading FastA file: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test/data/06.cds/GCA_000016625.faa.gz
    File contains 1579 sequences.
Running one-way comparisons.
[ 2021-02-24 10:07:19 -0500 ] GCA_000964845
Accessing SQLite3 file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.haai.db.
Temporal directory: /tmp/d20210224-10587-1lvtq0h.
Creating databases.
  Reading FastA file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.ess_genes.fa
    File contains 104 sequences.
  Reading FastA file: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test/data/07.annotation/01.function/01.essential/GCA_000964845.ess.faa
    File contains 104 sequences.
Running one-way comparisons.
Warning: [blastp] Examining 5 or more matches is recommended
Warning: [blastp] Examining 5 or more matches is recommended
Accessing SQLite3 file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.aai.db.
Temporal directory: /tmp/d20210224-11832-167fnvz.
Creating databases.
  Reading FastA file: /tmp/d20210224-5877-1wg61rv/GCA_000964845.proteins.fa
    File contains 2492 sequences.
  Reading FastA file: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test/data/06.cds/GCA_000964845.faa.gz
    File contains 2492 sequences.
Running one-way comparisons.
Checkpoint (metric = haai)
Checkpoint (metric = aai)
Checkpoint (metric = ani)

######[ stats ]######
# Date: 2021-02-24 10:08:13 -0500
# Host: localhost.localdomain
# MiGA: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1
# Project: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test
# Dataset: GCA_000964845
#------------
# raw_reads
# trimmed_fasta
# assembly
Contigs: 49
N50: 347385 bp
Total length: 2303093 bp
Longest sequence: 1137055 bp
G+C content: 32.39830089362436 %
X content: 0.0 %
G-C skew: 1.9763778155711285 %
A-T skew: 0.6056791249446025 %
# cds
Predicted proteins: 2492
Average length: 253.27969502407706 aa
Coding density: 82.21634992594741 %
Codon table: 11
# essential_genes
Completeness: 93.7 %
Contamination: 1.8 %
Quality: 84.7
# ssu
Ssu: 1
Complete ssu: 1
Max length: 1494
# distances
# taxonomy

Last error in miga-project.log (keeps doing over and over again...):

######[ clade_finding ]######
# Date: 2021-02-24 20:23:59 -0500
# Host: localhost.localdomain
# MiGA: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1
# Project: /home/bcampbell/Pelagibacterales/Pelagibacter_for_v7/original_fasta/Rickettsia/test
#------------
[ Wed Feb 24 20:24:02 2021 ] ==> Out base: miga-project <== 
Exception: Cannot add result, incomplete expected files.

DEBUG: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli/action/add_result.rb:23:in `perform'
DEBUG: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli/action.rb:32:in `launch'
DEBUG: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli.rb:177:in `launch'
DEBUG: /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/bin/miga:12:in `<main>'
/home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli/action/add_result.rb:23:in `perform': Cannot add result, incomplete expected files. (RuntimeError)
	from /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli/action.rb:32:in `launch'
	from /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli.rb:177:in `launch'
	from /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/bin/miga:12:in `<main>'
/home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli/action/run.rb:77:in `wait': Interrupt
	from /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli/action/run.rb:77:in `perform'
	from /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli/action.rb:32:in `launch'
	from /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/lib/miga/cli.rb:177:in `launch'
	from /home/bcampbell/anaconda3/envs/miga/share/rubygems/gems/miga-base-0.7.20.1/bin/miga:12:in `<main>'

Generates a MiGA.output file (haven't attempted to open it).

**Comment by jianshu93** [comment]
Dear Barb,

I am using the Conda version following the installation here: https://colab.research.google.com/drive/1ybCCPbbZtJ41HC_1yNYed8Yf-q9CDY5a

the index_wf works nicely for me and I have the Rdata for AAI and ANI. Luis Miguel may have other suggestions for you because he's working on a new release I think.

Thank you for your interest in MiGA.

Jianshu

**Comment by lmrodriguezr** [comment]
I'm closing this issue, but please feel free to reopen and/or just comment here.

**Comment by BJCampbelllab** [comment]
Thanks!  I’ll update and see what happens.

**Comment by BJCampbelllab** [comment]
Hi Luis,
I ended up removing the miga environment from conda by rm the environment/directory and am attempting to reinstall from these instructions:
https://manual.microbial-genomes.org/part2/requirements/conda

I got an error for scythe.  It was no longer found in faircloth-lab.



PackagesNotFoundError: The following packages are not available from current channels:

  - scythe

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/faircloth-lab/linux-64
  - https://conda.anaconda.org/faircloth-lab/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

I went to the anaconda page and searched for scythe, and that only gave me access to a scythe-score-counter (tpug).

Any suggestions?
Thanks!
Barb
