### ISSUE TITLE
Scythe no longer in conda

### ISSUE THREAD

**Issue by lmrodriguezr** [bio-miga/miga#125]
_Originally posted by @BJCampbelllab in https://github.com/bio-miga/miga/issues/124#issuecomment-788118818_

Hi Luis,
I ended up removing the miga environment from conda by rm the environment/directory and am attempting to reinstall from these instructions:
https://manual.microbial-genomes.org/part2/requirements/conda

I got an error for scythe.  It was no longer found in faircloth-lab.

PackagesNotFoundError: The following packages are not available from current channels:

  - scythe

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/faircloth-lab/linux-64
  - https://conda.anaconda.org/faircloth-lab/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

I went to the anaconda page and searched for scythe, and that only gave me access to a scythe-score-counter (tpug).

Any suggestions?
Thanks!
Barb

**Comment by lmrodriguezr** [comment]
Hello @BJCampbelllab ,

We're working on replacing scythe altogether, so this problem will soon disappear. However, in the meantime, I'd like to ask you: Do you want to process raw reads or only assembled genomes?

**Comment by BJCampbelllab** [comment]
Hi Luis,

I just have about 100 genomes (some assembled, some reference) that I want to get aai info for, so I can make a heatmap/matrix for publication.  I’ve done the ani with anvio.

Thanks!
Barb

**Comment by lmrodriguezr** [comment]
Perfect. Since you don't need read processing, my recommendation would be:
1. Update MiGA to the latest version (v0.7.26.0)
2. Initialize miga again using: `miga init --no-optional` (or if you want MyTaxa and RDP on, simply: `miga --no-read-processing`)
3. Now MiGA should work without problems as long as the input is assemblies

Also, when running the workflow, I'd strongly recommend using the flags `--fast` and `--haai-p fastaai`. These will become the default in the upcoming v1.0.

Related issues: #107 and #99

**Comment by BJCampbelllab** [comment]
Hi-
It’s not finding FastANI.

Any suggestions?
Barb

**Comment by lmrodriguezr** [comment]
Make sure you have all the rest of the prerequisites (excluding those for read processing):
```bash
conda install -y -c conda-forge r-base r
conda install -y --strict-channel-priority -c conda-forge ruby
conda install -y sqlite openjdk
conda install -y -c conda-forge -c bioconda \
  blast hmmer bedtools prodigal mcl barrnap \
  diamond krona fastani
```

And then just rerun:

```bash
gem install miga-base
miga init --no-optional
```

FastANI should be installed in the conda step and detected by `miga init` in the last step. The MiGA version should be `0.7.26.2` (there was an issue with the GitHub actions that prevented `v0.7.26.0` to ship with ancillary software, including FastAAI).


Best,
Miguel.

**Comment by BJCampbelllab** [comment]
Finally got it initialized.  I did a test with three genomes, and it finished quickly. However, the index.html file won’t open correctly.  Do I need to open it through a tunnel or anything?  Or, is the data (matrix) info I need in this file?

/data/09.distances/02.aai/miga-project.txt.gz

Thanks!

**Comment by lmrodriguezr** [comment]
Great!

To see the `index.html`, you could transfer that file as well as the `browse` folder. However, that's only there to help you navigate the files (and to show some of the summary statistics).

Yes, you are correct: the data you need is stored in `data/09.distances/02.aai/miga-project.txt.gz`. The format is a little strange, but you can easily transform it into a regular matrix in `R` using the `enveomics.R` package (which MiGA should have installed already):

```R
library('enveomics.R')
a <- read.table(gzfile('data/09.distances/02.aai/miga-project.txt.gz'), head = TRUE)

# Square AAI similarity matrix:
sim.aai <- as.matrix(enve.df2dist(a, 'a', 'b', 'value'))

# Or directly as a distance matrix:
dist.aai <- enve.df2dist(a, 'a', 'b', 'value', max.sim = 100)
```

Best,
Miguel.

**Comment by BJCampbelllab** [comment]
Thanks so much for all your help!  The real dataset is running as we speak with 40 threads.  I’ll let you know if I have any more issues.

Best,
Barb

**Comment by lmrodriguezr** [comment]
Dear Barb,
I'll close this issue now, but please feel free to reopen if you encounter any new problems (or if you continue to experience this one).

Best,
Miguel.

**Comment by BJCampbelllab** [comment]
Thanks Miguel,
Your suggestions worked perfectly!  I look forward to working with the new version when it comes out.
Best,
Barb
