### ISSUE TITLE
fail to run in the colab

### ISSUE THREAD

**Issue by Yun-Tianming** [bio-miga/miga#171]
![image](https://github.com/bio-miga/miga/assets/80634739/0ecb2e0d-5488-4b5a-9833-cba46f0df249)
I fail to run the example file(MiGA_1.0_conda_installation.ipynb) in the colab, how to solve this?

**Comment by lmrodriguezr** [comment]
Thank you for letting us know! We're updating the docs and should have a working notebook up soon

**Comment by lmrodriguezr** [comment]
We have replaced the notebook and the new one is ready to be used. I'm closing the issue now, but please feel free to reopen if it doesn't work for you.

**Comment by Yun-Tianming** [comment]
> We have replaced the notebook and the new one is ready to be used. I'm closing the issue now, but please feel free to reopen if it doesn't work for you.

Got it. Thanks for your efforts deeply!
