### ISSUE TITLE
Web server results download

### ISSUE THREAD

**Issue by ranitori** [bio-miga/miga#175]
Hi,
Is there a way to download all of the results from an NCBI Prok analysis done on the website, rather than downloading many individual files?
Thanks.

**Comment by lmrodriguezr** [comment]
Hello @ranitori ,

There is no easy way of doing this from MiGA Online, but you can do it from the MiGA Gateway:
https://gateway.microbial-genomes.org/

In there, you can simply launch an analysis with one or more genomes at a time, and then download all the results in a single zipped file.


I hope this helps.
Best wishes,
Miguel.
