### ISSUE TITLE
Error when uploading Genome on NCBI Prok

### ISSUE THREAD

**Issue by aaronlohar** [bio-miga/miga#177]
Hi there,

Whenever I click the upload genome to NCBI Prok, there will be an error saying "We're sorry, but something went wrong. If you are the application owner check the logs for more information."  It has been happening for the last 4 months.
I will need your help to fix the server as I would like to run more genome assemblies on your platform. Thank you :)
<img width="949" alt="Screenshot 2024-05-10 150211" src="https://github.com/bio-miga/miga/assets/169433312/32efadbb-16b8-459c-a117-34b057837087">

**Comment by lmrodriguezr** [comment]
Dear @aaronlohar ,

Thank you for your report. The servers were down for maintenance and a connection failed to reload. Service has now been reestablished, please try again.

Also, please note that a new MiGA server with up-to-date databases is also available at:
https://uibk.microbial-genomes.org/

Best wishes,
Miguel.
