### ISSUE TITLE
miga init not consistently sourcing .miga_modules

### ISSUE THREAD

**Issue by lmrodriguezr** [bio-miga/miga#54]
For Ruby libs and R packages

**Comment by majusogi** [comment]
Hi, I am getting this error when I do miga init: 

Should I include MyTaxa modules? (yes / no)  [yes] > yes
Testing Ruby (Required version: 1.9+)... sh: 1: source: not found
Where can I find it?  [.] > 
I cannot find ruby. sh: 1: source: not found
Where can I find it?  [.] > 

Thanks, 

Juliana

**Comment by lmrodriguezr** [comment]
I believe this was resolved during the `miga init` refactoring. I'll close this issue, but please reopen if reproduced with a recent version.
