### ISSUE TITLE
miga init crashing (source not found)

### ISSUE THREAD

**Issue by lmrodriguezr** [bio-miga/miga#60]
Should I include MyTaxa modules? (yes / no)  [yes] > yes
Testing Ruby (Required version: 1.9+)... sh: 1: source: not found
Where can I find it?  [.] > 
I cannot find ruby. sh: 1: source: not found
Where can I find it?  [.] > 

Thanks, 

Juliana

_Originally posted by @majusogi in https://github.com/bio-miga/miga/issues/54#issuecomment-439524668_

**Comment by lmrodriguezr** [comment]
Is there anything in `~/.miga_modules`? Please paste here it's contents if it exists (remove anything sensitive like usernames and hostnames).

**Comment by majusogi** [comment]
#!/bin/bash

shopt -s expand_aliases

# Enable software installed in this user
export PATH="$HOME/apps/bin:$PATH"

# Enable MyTaxa
export PATH="$HOME/apps/MyTaxa:$PATH"

# Workaround for broken KronaTools in the cluster
alias ktImportText="perl -I$HOME/shared3/apps/KronaTools-2.5/lib/ \
  $HOME/shared3/bin/ktImportText"

**Comment by majusogi** [comment]
Hi @lmrodriguezr 
Any feedback about this error? 

Thanks in advance!

**Comment by lmrodriguezr** [comment]
I don't see anything wrong with the file, but please run the following commands and tell me what's the output:

```bash
source ~/.miga_modules
```

Then run `miga c` and execute the following in the irb prompt (notice the backticks):
```ruby
`source "#{ENV['HOME']}/.miga_modules"`
```

**Comment by lmrodriguezr** [comment]
Does the first command work?

> ```bash
> source ~/.miga_modules
> ```

**Comment by majusogi** [comment]
yes, it worked

**Comment by lmrodriguezr** [comment]
Is this Ubuntu? I think it may be an issue with /bin/dash
I'll change this to `.`

**Comment by lmrodriguezr** [comment]
Fix confirmed. Thanks for the report @majusogi !
