### ISSUE TITLE
Error: Database was built with a different version of diamond as is incompatible.

### ISSUE THREAD

**Issue by majusogi** [bio-miga/miga#61]
Hi, 
I am getting this error in the .log file in mytaxa_scan:

more SBI1554.log
MiGA: /home/ubuntu/Downloads/miga
Project: /home/ubuntu/Prioritized.candidates.2018/Hafnia
diamond v0.9.4.105 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 2
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 5
Temporary directory: /tmp/MiGA.dJC0vMnl2bQS
Opening the database...  [0.002349s]
**Error: Database was built with a different version of diamond as is incompatible.**

Thanks,

**Comment by lmrodriguezr** [comment]
Hello,

It looks like you're using diamond v0.9.4.105, which is not supported by MiGA.
You'll need at diamond v0.9.20 or newer.

See: https://github.com/bio-miga/miga/blob/master/utils/requirements.txt#L17
