### ISSUE TITLE
How to use MiGA CLI

### ISSUE THREAD

**Issue by Russel88** [bio-miga/miga#66]
I have installed MiGA locally, however it is unclear how it should be run.

Could you give a synopsis of what to run if I want to compare a genome to RefSeq for example?

Cheers,
Jakob

**Comment by lmrodriguezr** [comment]
Hello @Russel88 
Sorry this took longer than expected, but we now have a simplified (and documented) method to obtain and use reference databases. See https://manual.microbial-genomes.org/part6/classify_wf

The new methods have been released in v0.5.0.0, please make sure you have at least this version.

Thanks!
Miguel.
