### ISSUE TITLE
MiGa online is down 

### ISSUE THREAD

**Issue by magnuson1** [bio-miga/miga#83]
Hi,
For the past few days, access to MiGa Online through microbial-genomes.org has been down. I receive only an error message that says:

This website is under heavy load (queue full)

We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

Any chance that it will be back up soon?

**Comment by lmrodriguezr** [comment]
Hello @magnuson1 
Thanks for letting us know! There was a hanging project that caused a bottleneck in the sever, but it's now back online.
