### ISSUE TITLE
conda envirenment containing all prerequisits

### ISSUE THREAD

**Issue by uloeber** [bio-miga/miga#96]
Hi,
I'm trying to install MIGA on our server right now. I am desperately failing.
I just notices I needed to downgrade python to 3.7, because solexaqa does not work with v3.8; need to upgrade R to at least 3.4, because of vegan (which I don't know whether it was mentioned in the docs.), and I am ending with:

`miga init`
#/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sqlite3 (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /data/AG_group/user/migaapps/miga/lib/miga/dataset/result.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /data/AG_group/user/migaapps/miga/lib/miga/dataset.rb:7:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /data/AG_group/user/migaapps/miga/lib/miga/project.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /data/AG_group/user/migaapps/miga/lib/miga.rb:7:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /data/AG_group/user/migaapps/miga/bin/miga:7:in `<main>'

Would you be willing to create a container with all its dependencies?
Do you know what might have been the issue in my case?
Thanks in advance!
Ulrike

**Comment by uloeber** [comment]
ruby update to 2.6
`gem install bundler`
Fetching: bundler-2.1.4.gem (100%)
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.
An error occurred while installing json (2.3.0), and Bundler cannot continue.
Make sure that `gem install json -v '2.3.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  codeclimate-test-reporter was resolved to 1.0.9, which depends on
    simplecov was resolved to 0.13.0, which depends on
      json

I tried both gem install and via github from source.

**Comment by lmrodriguezr** [comment]
Hello Ulrike,

Did you try using the `conda` instructions [here](https://manual.microbial-genomes.org/part2/requirements/conda)? Or are you installing everything from scratch?

We do have a container, maintained by @FangYuan0059 : https://hub.docker.com/r/fyuan277/miga_cli, but we're still testing it in-house which is why we don't currently reference it in the docs.

As for your specific error, it looks like you're missing the `json` gem. If your Ruby is properly configured it should be a matter of running `gem install json`, but I've had some issues with this gem in the past. Which OS do you have?

M

**Comment by uloeber** [comment]
Hi,yes I used these instructions, failed and tried installing from scratch.
    Am Donnerstag, 14. Mai 2020, 21:42:49 MESZ hat Luis M Rodriguez-R <notifications@github.com> Folgendes geschrieben:  
 
 


Hello Ulrike,

Did you try using the conda instructions here? Or are you installing everything from scratch?

We do have a container, maintained by @FangYuan0059 : https://hub.docker.com/r/fyuan277/miga_cli, but we're still testing it in-house which is why we don't currently reference it in the docs.

As for your specific error, it looks like you're missing the json gem. If your Ruby is properly configured it should be a matter of running gem install json, but I've had some issues with this gem in the past. Which OS do you have?

M

**Comment by lmrodriguezr** [comment]
What was the exact point and error message of the failure with `conda`?

**Comment by uloeber** [comment]
MIGA init fails after installing dependencies using conda
`miga init`
Traceback (most recent call last):
	14: from /data/AG_group/user/migaapps/miga/bin/miga:7:in `<main>'
	13: from /home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /data/AG_group/user/migaapps/miga/lib/miga.rb:7:in `<top (required)>'
	10: from /home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /data/AG_group/user/migaapps/miga/lib/miga/project.rb:4:in `<top (required)>'
	 7: from /home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /data/AG_group/user/migaapps/miga/lib/miga/dataset.rb:7:in `<top (required)>'
	 4: from /home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /data/AG_group/user/migaapps/miga/lib/miga/dataset/result.rb:1:in `<top (required)>'
	 1: from /home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/uloeber/anaconda3/envs/miga/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sqlite3 (LoadError)

**Comment by lmrodriguezr** [comment]
Ok, so that error is related to a missing gem (`json`). Did you install the miga gem first?
```
gem install miga-base
```

**Comment by lmrodriguezr** [comment]
If yes, was there an error in that command?

**Comment by uloeber** [comment]
===[ Welcome to MiGA, the Microbial Genome Atlas ]===

I'm the initialization script, and I'll sniff around your computer to
make sure you have all the requirements for MiGA data processing.

Would you like to see all the requirements before starting? (yes / no) [no] > 
I found a previous configuration. Do you want to continue? (yes / no) [yes] > 
Found bash configuration script: /home/uloeber/.miga_modules

Looking for requirements:
Should I include MyTaxa modules? (yes / no) [yes] > 
Testing Ruby (Required version: 2.3+)... 
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Where can I find it? [.] > 


conda init bash
No action taken
Never had conda issues before
`conda activate miga` works fine
`uname -r`
3.10.0-1127.el7.x86_64

**Comment by lmrodriguezr** [comment]
Possibly `conda` is not initialized by default in new sub-shells. Try this:

```bash
echo 'conda init bash
conda activate miga' > ~/.miga_modules
```

**Comment by uloeber** [comment]
Looks like it worked. Thank you for your support!

**Comment by lmrodriguezr** [comment]
It's very strange that you get the exact same error.
Does this command throw any errors?
```bash
echo '`conda init bash && conda activate miga`' | miga console
```

How about this one?

```bash
echo '`eval "$(conda shell.bash hook)" && conda activate miga`' | miga console
```

**Comment by lmrodriguezr** [comment]
We have recently released Google Collab notebooks including live installation code for both [`conda`](https://manual.microbial-genomes.org/part2/requirements/conda#live-notebook) and [`apt-get`](https://manual.microbial-genomes.org/part2/requirements/apt-get#live-notebook).

I have also [updated the manual](https://manual.microbial-genomes.org/part2/requirements/conda#essentials) to reflect the python version restriction you mentioned.

I'm closing this issue for now but feel free to reopen if the issue persists.
