### ISSUE TITLE
Make --fast settings the default

### ISSUE THREAD

**Issue by jianshu93** [bio-miga/miga#99]
Hi Miguel,
I have ~700 MAGs for the dereplication workflow using blast+ as search engine instead of diamond and fastANI. It takes more than 24 hour or more using 36 processes and 2 threads for each process. The blastp command takes more than 12 hours and I am not quite sure what it does. I am trying to find more information in the manual of MiGA about each step of this workflow but failed. Do you think making fastANI and diamond default method a good advice? For most users, they do not expect this workflow to run that longer and perhaps they will not look at the help message in detail at their first try (dRep and galah use gANI and fastANI by default without mentioning blast+). Also, this workflow also run quality check right? Is a separate quality check workflow possible?

Thanks,

Jianshu

**Comment by lmrodriguezr** [comment]
Note: This will require making Diamond and FastANI mandatory requirements
